/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

interface EarthProps {
  scale?: [number, number, number];
  position?: [number, number, number];
  rotation?: [number, number, number];
}

export function EarthObject({
  // scale = [15,15,15],
  // position = [0, 0, 0],
  // rotation = [0, 0, 0]
}: EarthProps) {
  const { nodes, materials } = useGLTF('/models/earth.glb') as unknown as {
    nodes: {
      earth: THREE.Mesh;
    };
    materials: {
      'Default OBJ': THREE.Material;
    };
  };

  // Enhance material for day/night effect
  const earthMaterial = useMemo(() => {
    const mat = materials['Default OBJ'].clone();
    if (mat instanceof THREE.MeshStandardMaterial) {
      mat.emissive = new THREE.Color('#000000');
      mat.emissiveIntensity = 0;
      mat.roughness = 0.9;
      mat.metalness = 0;
      mat.side = THREE.FrontSide;
    }
    return mat;
  }, [materials]);

  // Cloud layer material
  const cloudMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      color: '#ffffff',
      transparent: true,
      opacity: 0.4,
      roughness: 1,
      metalness: 0,
      side: THREE.FrontSide,
    });
  }, []);

  // Night lights material (emissive for cities on dark side)
  const nightLightsMaterial = useMemo(() => {
    return new THREE.MeshBasicMaterial({
      color: '#ffaa00',
      transparent: true,
      opacity: 0.8,
      blending: THREE.AdditiveBlending,
      side: THREE.BackSide, // Render on the back side (night side)
    });
  }, []);

  // Atmosphere glow material
  const atmosphereMaterial = useMemo(() => {
    return new THREE.ShaderMaterial({
      transparent: true,
      side: THREE.BackSide,
      uniforms: {
        c: { value: 0.4 },
        p: { value: 4.5 },
        glowColor: { value: new THREE.Color('#4fc3f7') }
      },
      vertexShader: `
        varying vec3 vNormal;
        varying vec3 vPosition;
        void main() {
          vNormal = normalize(normalMatrix * normal);
          vPosition = position;
          gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
        }
      `,
      fragmentShader: `
        uniform vec3 glowColor;
        uniform float c;
        uniform float p;
        varying vec3 vNormal;
        varying vec3 vPosition;
        void main() {
          float intensity = pow(c - dot(vNormal, vec3(0, 0, 1.0)), p);
          gl_FragColor = vec4(glowColor, 1.0) * intensity;
        }
      `
    });
  }, []);

  if (!nodes.earth?.geometry) {
    console.log('Earth model mesh not found in GLTF file');
    return null;
  }

  const earthRadius = 0.003;

  return (
    <group dispose={null}>
      {/* Directional light simulating Sun - positioned to light Asia */}
      <directionalLight
        position={[20, 2, 5]} // Light from the East/right side
        intensity={3.5}
        color="#ffffff"
        castShadow
        shadow-mapSize-width={2048}
        shadow-mapSize-height={2048}
      />
      
      {/* Very subtle ambient light - only to prevent complete darkness */}
      <ambientLight intensity={0.05} color="#0a0a1a" />
      
      {/* Rim light for atmospheric glow on the night side */}
      <pointLight
        position={[-12, 0, 0]}
        intensity={0.4}
        color="#2563eb"
        distance={25}
        decay={2}
      />
      
      {/* Main Earth mesh */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.earth.geometry}
        material={earthMaterial}
        position={[0, 0.039, 0.017]}
        scale={earthRadius}
        rotation={[0, -Math.PI * 0.35, 0.1]} // Rotate to show Asia on lit side, USA on dark side
      />

      {/* Cloud layer - slightly larger sphere */}
      <mesh
        position={[0, 0.039, 0.017]}
        rotation={[0, -Math.PI * 0.35, 0.1]}
        scale={earthRadius * 1.01}
      >
        <sphereGeometry args={[333.33, 64, 64]} />
        <meshStandardMaterial
          transparent
          opacity={0.3}
          color="#ffffff"
          roughness={1}
          metalness={0}
          depthWrite={false}
        />
      </mesh>

      {/* Night city lights on dark side */}
      <mesh
        position={[0, 0.039, 0.017]}
        rotation={[0, -Math.PI * 0.35 + Math.PI, 0.1]} // Rotated to opposite side
        scale={earthRadius * 1.002}
      >
        <sphereGeometry args={[333.33, 64, 64]} />
        <meshBasicMaterial
          transparent
          opacity={0.6}
          color="#ffaa00"
          blending={THREE.AdditiveBlending}
          side={THREE.FrontSide}
        />
      </mesh>

      {/* Atmospheric glow */}
      <mesh
        position={[0, 0.039, 0.017]}
        rotation={[0, -Math.PI * 0.35, 0.1]}
        scale={earthRadius * 1.15}
      >
        <sphereGeometry args={[333.33, 64, 64]} />
        <primitive object={atmosphereMaterial} attach="material" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/earth.glb')