/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

interface EarthProps {
  scale?: [number, number, number];
  position?: [number, number, number];
  rotation?: [number, number, number];
}

export function EarthObject({
  // scale = [15,15,15],
  // position = [0, 0, 0],
  // rotation = [0, 0, 0]
}: EarthProps) {
  const { nodes, materials } = useGLTF('/models/earth.glb') as unknown as {
    nodes: {
      earth: THREE.Mesh;
    };
    materials: {
      'Default OBJ': THREE.Material;
    };
  };

  if (!nodes.earth?.geometry) {
    console.log('Earth model mesh not found in GLTF file');
    return null;
  }

  return (
    <group dispose={null}>
    <mesh
        castShadow
        receiveShadow
        geometry={nodes.earth.geometry}
        material={materials['Default OBJ']}
        position={[0, 0.039, 0.017]}
        scale={0.003}
        rotation={[0, 0, 0]}
      />
      </group>
  )
}

useGLTF.preload('/models/earth.glb')