/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import * as THREE from "three";
import { Mesh } from "three";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";
import { OrbitControls } from "@react-three/drei";
// import { MeshProps } from "@react-three/fiber";

interface IcebergProps {
  scale?: [number, number, number];
  position?: [number, number, number];
  rotation?: [number, number, number];
}

export function IcebergObject({ scale, position, rotation }: IcebergProps) {
  const { nodes, materials } = useGLTF('/models/frosted_iceberg_final.glb') as unknown as {
    nodes: {
      iceberg: THREE.Mesh;
    };
    materials: {
      'Frosted Ice': THREE.Material;
    };
  };
  return (
     <mesh
        castShadow
        receiveShadow
        geometry={nodes.iceberg.geometry}
        material={materials['Frosted Ice']}
        position={[0, -2, 0]}
        scale={[1, 1, 1]}
        rotation={[0, 0, 0]} 
      />
  )
}

useGLTF.preload('/models/frosted_iceberg_final.glb')