/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/* eslint-disable @typescript-eslint/no-unused-vars */
"use client";

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

interface IcebergProps {
  scale?: [number, number, number];
  position?: [number, number, number];
  rotation?: [number, number, number];
}

export function IcebergObject({ scale, position, rotation }: IcebergProps) {
  const { nodes, materials } = useGLTF('/models/frosted_iceberg_final.glb') as unknown as {
    nodes: {
      iceberg: THREE.Mesh;
    };
    materials: {
      'Frosted Ice': THREE.Material;
    };
  };
  return (
     <mesh
        castShadow
        receiveShadow
        geometry={nodes.iceberg.geometry}
        material={materials['Frosted Ice']}
        position={[0, -2, 0]}
        scale={[1, 1, 1]}
        rotation={[0, 0, 0]} 
      />
  )
}

useGLTF.preload('/models/frosted_iceberg_final.glb')