/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

interface LunarLandProps {
  scale?: [number, number, number];
  position?: [number, number, number];
  rotation?: [number, number, number];
}

export function LunarLandObject({
  scale = [0.0003, 0.0003, 0.0003],
  position = [0, -1.5, 0],
  rotation = [-100, 0, 0] // -60 degrees for horizon view
}: LunarLandProps) {
  const { nodes, materials } = useGLTF('/models/lunar_land.glb') as unknown as {
    nodes: {
      Copernicus_LP_2_0: THREE.Mesh;
      'Copernicus_LP_Material_#64_0': THREE.Mesh;
    };
    materials: {
      material: THREE.Material;
      Material_64: THREE.Material;
    };
  };

  if (!nodes.Copernicus_LP_2_0?.geometry || !nodes['Copernicus_LP_Material_#64_0']?.geometry) {
    console.error('Lunar Land model mesh not found in GLTF file');
    return null;
  }

  return (
    <group position={position} rotation={rotation} scale={scale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Copernicus_LP_2_0.geometry}
        material={materials.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Copernicus_LP_Material_#64_0'].geometry}
        material={materials.Material_64}
      />
    </group>
  )
}

useGLTF.preload('/models/lunar_land.glb')