/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

interface MoonProps {
  scale?: [number, number, number];
  position?: [number, number, number];
  rotation?: [number, number, number];
}

export function MoonObject({
  // scale = [15,15,15],
  // position = [0, 0, 0],
  // rotation = [0, 0, 0]
}: MoonProps) {
  const { nodes, materials } = useGLTF('/models/the_moon_4k.glb') as unknown as {
    nodes: {
      Object_2: THREE.Mesh;
    };
    materials: {
      'moon': THREE.Material;
    };
  };

  if (!nodes.Object_2?.geometry) {
    console.log('Earth model mesh not found in GLTF file');
    return null;
  }

  return (
    <group dispose={null}>
    <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['moon']}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, 0.039, 0.017]}
        // scale={1}
      />
      </group>
  )
}

useGLTF.preload('/models/the_moon_4k.glb')